### ISSUE TITLE
Add letter ñ (eñe)

### ISSUE THREAD

**Issue by santiagotsp** [googlefonts/roboto#312]
The letter eñe (ñ) is part of the Spanish alphabet.
Examples of words:
year - año
brother in law - cuñado
old - añejo

**Comment by fitojb** [comment]
I think you are confused due to (maybe) downloading an extremely subsetted version of the font from elsewhere. (Please only file bugs relating to this repository’s files.)

Ñ ñ have always been part of the typeface, and in fact, of nearly all typefaces in existence that support the Latin alphabet, because those characters are part of the Latin-1 character set, which was first released in 1987.

**Comment by davelab6** [comment]
Thanks @fitojb for explaining this and in similar issue #296 and elsewhere :)
